### ISSUE TITLE
vod ve seriesde  secili olmayan categori  geliliyor

### ISSUE THREAD

**Issue by adilem** [emre1393/xtreamui-things#16]
enigma2.php vod ve seriesde geliyor boş categoriler secili olmasa bile geliyor
player_api.php den ise sadece seriesde  boş categoriler secili olmasa bile geliyor

lütfen düzeltirmisin ustam

**Comment by emre1393** [comment]
ona benim yapabileceğim bir şey yok, orjinal xc backend fonksiyonu o şakilde çalışıyor.

**Comment by adilem** [comment]
emre ustam yanlız gta panelde XUİ ONE de player_api.php apisinden gelmiyor secili olmayanlar
sadece enigma2.php php den geliyor ona görde sende yapamazmısın sana zahmet  yada gta player_api.php  senin panel uyarlama şansın yokmu

________________________________
Gönderen: Emre ***@***.***>
Gönderildi: 9 Temmuz 2022 Cumartesi 02:45
Kime: emre1393/xtreamui-things ***@***.***>
Bilgi: adilem ***@***.***>; Author ***@***.***>
Konu: Re: [emre1393/xtreamui-things] vod ve seriesde secili olmayan categori geliliyor (Issue #16)


ona benim yapabileceğim bir şey yok, orjinal xc backend fonksiyonu o şakilde çalışıyor.
