### ISSUE TITLE
Change database user and port

### ISSUE THREAD

**Issue by joring** [emre1393/xtreamui-things#2]
Hi, can you make phyton tools who can change database user and database port on all load balancers?

**Comment by emre1393** [comment]
try this, i didn't test  it yet but i forked it from update_main_ip.py script and config.py script

**Comment by emre1393** [comment]
> Hi, can you make phyton tools who can change database user and database port on all load balancers?

try this, i didn't test it yet but i forked it from update_main_ip.py script and config.py script
https://github.com/emre1393/xtreamui-things/blob/master/pytools/update_main_info_on_lbs.py

**Comment by joring** [comment]
You are best, great job, thank you!
